routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

// Admin Panel Links***********************************************************************

// General Pages
use App\Http\Controllers\Admin\General\PageController;
use App\Http\Controllers\Admin\General\PageDetailController;
use App\Http\Controllers\Admin\General\ViewController;
use App\Http\Controllers\Admin\General\UserController;
use App\Http\Controllers\Admin\General\ArticleController;
use App\Http\Controllers\Admin\General\PostController;
use App\Http\Controllers\Admin\General\MenuController;
use App\Http\Controllers\Admin\General\MenuItemController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\TestController;


// Dynamic Pages
use App\Http\Controllers\MultiController;
use App\Http\Controllers\WebController;

// Route::group(['middleware'=>['ipcheck']], function() {
    Auth::routes();
    //Admin Panel Routes
    Route::get('/dashboard', [App\Http\Controllers\Admin\HomeController::class, 'index'])->name('dashboard');
    
    // General Pages
    Route::post('/pageinc/{id}', [App\Http\Controllers\Admin\General\PageController::class, 'incCount']);
    Route::post('/pagedesc/{id}', [App\Http\Controllers\Admin\General\PageController::class, 'descCount']);
    Route::post('/articleinc/{id}', [App\Http\Controllers\Admin\General\ArticleController::class, 'incCount']);
    Route::post('/articledesc/{id}', [App\Http\Controllers\Admin\General\ArticleController::class, 'descCount']);
    Route::post('/menuIteminc/{id}', [App\Http\Controllers\Admin\General\MenuItemController::class, 'incCount']);
    Route::post('/menuItemdesc/{id}', [App\Http\Controllers\Admin\General\MenuItemController::class, 'descCount']);
    Route::get('/article-list/{id}', [App\Http\Controllers\Admin\General\ArticleController::class, 'index'])->name('article');
    Route::post('/add-custom-post', [App\Http\Controllers\Admin\General\CustomPostController::class, 'addCustomPost']);
    Route::post('/list-custom-post', [App\Http\Controllers\Admin\General\CustomPostController::class, 'listCustomPost']);
    Route::post('/delete-custom-post/{id}', [App\Http\Controllers\Admin\General\CustomPostController::class, 'deleteCustomPost']);
    Route::post('/get-custom-post/{id}', [App\Http\Controllers\Admin\General\CustomPostController::class, 'getCustomPost']); 
    Route::post('/update-custom-post/{id}', [App\Http\Controllers\Admin\General\CustomPostController::class, 'updateCustomPost']); 
    Route::resource('page', PageController::class);
    // Route::resource('pagedetail', PageDetailController::class);
    Route::resource('view', ViewController::class);
    Route::resource('user', UserController::class);
    Route::resource('menu', MenuController::class);
    Route::resource('menuitem', MenuItemController::class);
    Route::resource('article', ArticleController::class);

    Route::resource('test', TestController::class);
    
    // End Admin Panel Links ***********************************************************************    
// });

Route::get('/en/{slug}' , [MultiController::class , 'enShow'])->where('slug', '.*');
Route::get('/ur/{slug}' , [MultiController::class , 'urShow'])->where('slug', '.*');

Route::get('/', [WebController::class , 'index']);
Route::post('/contact', [ContactController::class , 'contact'])->name('contact');
Route::post('/contact-claim', [ContactController::class , 'contactClaim'])->name('contact-claim');

 // Website route start  *******************   
//  Route::get('/', [WebController::class, 'index'])->name('/');
//  Route::get('about-us', [WebController::class, 'aboutUs'])->name('about-us');
//  Route::get('bod-and-management', [WebController::class, 'bodandManagement'])->name('bod-and-management');

app/Models/Admin/General/Article.php
<?php

namespace App\Models\Admin\General;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;

    protected $table = "article";
}

app/Models/Admin/General/CustomPost.php
<?php

namespace App\Models\Admin\General;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CustomPost extends Model
{
    use HasFactory;

    protected $table = "custom_fields";
}

app/Models/Admin/General/Menu.php
<?php

namespace App\Models\Admin\General;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    use HasFactory;

    protected $primaryKey = 'id';

    protected $table = "menu";

    protected $fillable = ['title_en','title_ur'];
}

app/Models/Admin/General/MenuItem.php
<?php

namespace App\Models\Admin\General;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MenuItem extends Model
{
    use HasFactory;

    protected $primaryKey = 'id';

    protected $table = "menu_item";

    protected $fillable = ['title_en','title_ur'];
}

app/Models/Admin/General/Page.php
<?php

namespace App\Models\Admin\General;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Page extends Model
{
    use HasFactory;

    protected $table = "pages";

    public function url(){
        return $this->hasOne(Urls::class);
    }

    public function customPost(){
        return $this->belongsTo(CustomPost::class);
    }
}

app/Http/Controllers/Admin/General/ArticleController.php
<?php

namespace App\Http\Controllers\Admin\General;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;
use App\Models\Admin\General\Article;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use DataTables;

class ArticleController extends Controller
{

    public function index(Request $request)
    {
        $id = Auth::id();
        if($id)
        {
            if ($request->ajax()) {
                $data =  Article::latest()->where('page_id','=',$request->id)->where("status", "=", 1)->get();
                return Datatables::of($data)
                        ->addIndexColumn()
                        ->addColumn('action', function($row){
                            $btn = '<a href="../article/'.$row->id.'/edit" class="edit btn btn-primary btn-sm">Edit</a><button onclick="mdelete('.$row->id.',this)" class="delete btn btn-danger btn-sm">Delete</button>';
                            return $btn;
                        })
                        ->rawColumns(['action'])
                        ->make(true);
            }
            return view('admin.general.article.index');
        } else {
            return view('admin.auth.login');
        }
    }

    public function create()
    {
        $id = Auth::id();
        if($id)
        {
            
            $parents = DB::table('pages')
            ->join('url', 'pages.id', '=', 'url.page_id')
            ->select('url.path','pages.title_en')
            ->get();
            return view('admin.general.article.create',compact('parents'));
        } else {
            return view('admin.auth.login');
        }
    }

    public function store(Request $request)
    {
        $id = Auth::id();
        if($id)
        {
            try {
                if($request->title_en != ""){
                    $mArticle = new Article;
                    $mArticle->page_id = $request->page_id;
                    $mArticle->title_en = $request->title_en;
                    $mArticle->description_en = $request->descen;
                    $mArticle->link_type_en = $request->linktype_en;
                    $mArticle->link_text_en = $request->link_text_en;
                    $mArticle->position_en = $request->position_en;
                    $mArticle->grid_class_en = $request->grid_class_en;
                    $mArticle->title_ur = $request->title_ur;
                    $mArticle->description_ur = $request->descur;
                    $mArticle->position_ur = $request->position_ur;
                    $mArticle->grid_class_ur = $request->grid_class_ur;
                    $mArticle->classes = $request->classes;
                    $mArticle->link_text_ur = $request->link_text_ur;
                    $mArticle->buy_link = $request->buy_link;
                    if($request->linktxt_ur != NULL){
                        $mArticle->link_ur = $request->linktxt_ur;
                    }else {
                        $mArticle->link_ur = $request->linksdp_ur;
                    }
                    if($request->linktxt_en != NULL){
                        $mArticle->link_en = $request->linktxt_en;
                    }else {
                        $mArticle->link_en = $request->linksdp_en;
                    }
                    $mArticle->link_type_ur = $request->linktype_ur;
                    if($request->doc_en != ""){
                        if( strpos($request->doc_en, ',') !== false ) {
                            $mArticle->image_en = $request->doc_en; 
                        }else{
                            $mArticle->image_en = '["'.$request->doc_en.'"]';  
                        }
                    } else {
                        $mArticle->image_en = "[]";
                    }
                    if($request->doc_ur != ""){
                        if( strpos($request->doc_ur, ',') !== false ) {
                            $mArticle->image_ur = $request->doc_ur; 
                        }else{
                            $mArticle->image_ur = '["'.$request->doc_ur.'"]';  
                        }
                    } else {
                        $mArticle->image_ur = "[]";
                    }
                    if($request->image_mobile_en != ""){
                        if( strpos($request->image_mobile_en, ',') !== false ) {
                            $mArticle->image_mobile_en = $request->image_mobile_en; 
                        }else{
                            $mArticle->image_mobile_en = '["'.$request->image_mobile_en.'"]';
                        }
                    } else {
                        $mArticle->image_mobile_en = "[]";
                    }
                    if($request->image_mobile_ur != ""){
                        if( strpos($request->image_mobile_ur, ',') !== false ) {
                            $mArticle->image_mobile_ur = $request->image_mobile_ur; 
                        }else{
                            $mArticle->image_mobile_ur = '["'.$request->image_mobile_ur.'"]';
                        }
                    } else {
                        $mArticle->image_mobile_ur = "[]";
                    }
                    if($request->file_en != ""){
                        if( strpos($request->file_en, ',') !== false ) {
                            $mArticle->file_en = $request->file_en; 
                        }else{
                            $mArticle->file_en = '["'.$request->file_en.'"]';
                        }
                    } else {
                        $mArticle->file_en = "[]";
                    }
                    if($request->file_ur != ""){
                        if( strpos($request->file_ur, ',') !== false ) {
                            $mArticle->file_ur = $request->file_ur; 
                        }else{
                            $mArticle->file_ur = '["'.$request->file_ur.'"]';
                        }
                    } else {
                        $mArticle->file_ur = "[]";
                    }
                    $mArticle->save();
                    return "success";
                } else {
                    return "error";
                }
            } catch (\Throwable $th) {
                return $th;
            }
        } else {
            return view('admin.auth.login');
        }
    }

    public function show(Article $article)
    {
        //
    }

    public function edit(Article $article)
    {
        $id = Auth::id();
        if($id)
        {
            $parents = DB::table('pages')
            ->join('url', 'pages.id', '=', 'url.page_id')
            ->select('url.path','pages.title_en')->distinct()
            ->get();
            $custom_posts = DB::table('custom_fields')->select("*")->where("status", "=", 1)->where('parent_type','=','article')->where("parent_id", "=", $article->id)->get();
            return view('admin.general.article.edit',compact('article','parents','custom_posts'));
        } else {
            return view('admin.auth.login');
        }
    }

    public function update(Request $request, Article $Article)
    {
        $id = Auth::id();
        if($id)
        {
            try {
                if($request->title_en != ""){
                    $mArticle = Article::firstOrNew(['id' => $Article->id]);
                    $mArticle->page_id = $request->page_id;
                    $mArticle->title_en = $request->title_en;
                    $mArticle->description_en = $request->descen;
                    $mArticle->link_type_en = $request->linktype_en;
                    $mArticle->link_text_en = $request->link_text_en;
                    $mArticle->position_en = $request->position_en;
                    $mArticle->grid_class_en = $request->grid_class_en;
                    $mArticle->title_ur = $request->title_ur;
                    $mArticle->description_ur = $request->descur;
                    $mArticle->position_ur = $request->position_ur;
                    $mArticle->grid_class_ur = $request->grid_class_ur;
                    $mArticle->classes = $request->classes;
                    $mArticle->link_text_ur = $request->link_text_ur;
                    $mArticle->buy_link = $request->buy_link;
                    if($request->linktxt_ur != ""){
                        $mArticle->link_ur = $request->linktxt_ur;
                    }else {
                        $mArticle->link_ur = $request->linksdp_ur;
                    }
                    if($request->linktxt_en != NULL){
                        $mArticle->link_en = $request->linktxt_en;
                    }else {
                        $mArticle->link_en = $request->linksdp_en;
                    }
                    $mArticle->link_type_ur = $request->linktype_ur;
                    if($request->docen != ""){
                        $mArticle->image_en =  explode(",",$request->docen);
                    } else {
                        $mArticle->image_en = [];
                    }
                    if($request->docur != ""){
                        $mArticle->image_ur =  explode(",",$request->docur);
                    } else {
                        $mArticle->image_ur = [];
                    }
                    if($request->imgmoben != ""){
                        $mArticle->image_mobile_en =  explode(",",$request->imgmoben);
                    } else {
                        $mArticle->image_mobile_en = [];
                    }
                    if($request->imgmobur != ""){
                        $mArticle->image_mobile_ur =  explode(",",$request->imgmobur);
                    } else {
                        $mArticle->image_mobile_ur = [];
                    }
                    if($request->fileen != ""){
                        $mArticle->file_en =  explode(",",$request->fileen);
                    } else {
                        $mArticle->file_en = [];
                    }

app/Http/Controllers/Admin/General/CategoryController.php
<?php

namespace App\Http\Controllers\Admin\General;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories =  Category::all();
        return view('admin.general.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::where('parent_id', null)->get();
        return view('admin.general.category.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $category = new Category();
        $category->name = $request->name;
        if($request->parent_id != 0) $category->parent_id = $request->parent_id;
        $category->save();
        return Redirect('category');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $allCats = Category::all();
        return view('admin.general.category.edit', compact('category', 'allCats'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Category $category, Request $request)
    {
        $category->name = $request->name;
        $category->parent_id = $request->parent_id;
        $category->save();
        return Redirect('category');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)

    {
        $category->delete();
        return Redirect('category');
    }
}

resources/views/admin/general/view/create.blade.php
@extends('admin.layouts.app')
@section('content')
    @include('admin.partials.navbar')
    <div class="container-fluid page-body-wrapper">
        @include('admin.partials.sidebar')
        <div class="main-panel">
            <div class="content-wrapper">
                <div class="row">
                    <div class="col-12 grid-margin stretch-card">
                        <div class="card">
                            <div class="card-body">
                            <h4 class="card-title">View Create</h4>
                                <form method="POST" action="{{ route('view.store') }}" id="viewCreate" class="forms-sample row" enctype="multipart/form-data">
                                    @csrf
                                    <div class="form-group col-md-6">
                                        <label>Title<span class="text-danger">*</span></label>
                                        <input type="text" class="form-control" id="title" name="title" placeholder="Title">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label>Slug<span class="text-danger">*</span></label>
                                        <input type="text" class="form-control"  id="slug" name="slug" placeholder="Slug">
                                    </div>
                                    <div class="col-md-12 text-center">
                                        <button type="button" onclick="save()" class="btn btn-primary mr-2">Save</button>
                                        <a href="{{ route('view.index') }}" class="btn btn-light">Cancel</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @include('admin.partials.footer')            
        </div>
    </div>
    <script>
        $('#slug').on('keypress', function (event) {
            var regex = new RegExp("^[a-zA-Z0-9-]+$");
            var key = String.fromCharCode(!event.charCode ? event.which : event.charCode);
            if (!regex.test(key)) {
            event.preventDefault();
            return false;
            }
        });
        function save(){
            var formData  = new FormData(jQuery('#viewCreate')[0]);
            $.ajax({
                type:'POST',
                enctype: 'multipart/form-data',
                url:"{{ route('view.store') }}",
                headers: {
                    'X-CSRF-Token': '{{ csrf_token() }}',
                },
                data: formData,
                contentType: false,
                processData: false,
                success:function(data){
                    console.log(data);
                    if(data == 'success'){
                        swal({
                            title: "Success",
                            text: "Data added successfully.",
                            icon: "success",
                            buttons: "Ok",
                        })
                        .then((willDelete) => {
                            backUrl = (window.location+'').replace('/view/create', '/view');
                            window.location.href = backUrl;
                        });
                    }else if(data == 'data found') {
                        swal({
                            title: "Error",
                            text: "Please enter different slug.",
                            icon: "error",
                            button: "Ok",
                        });
                    } else {
                        swal({
                            title: "Error",
                            text: "Please fill required fields.",
                            icon: "error",
                            button: "Ok",
                        });
                    }
                }
            });
        }
    </script>
@endsection

resources/views/admin/general/view/edit.blade.php
@extends('admin.layouts.app')
@section('content')
    @include('admin.partials.navbar')
    <div class="container-fluid page-body-wrapper">
        @include('admin.partials.sidebar')
        <div class="main-panel">
            <div class="content-wrapper">
                <div class="row">
                    <div class="col-12 grid-margin stretch-card">
                        <div class="card">
                            <div class="card-body">
                            <h4 class="card-title">
                            <h4 class="card-title">View Edit</h4>
                                <form method="POST" action="{{ route('view.update',$view->id) }}" id="viewEdit" class="forms-sample row" enctype="multipart/form-data">
                                    @csrf
                                    @method('PUT')
                                    <input type="hidden" value="{{ $view->id }}" id="id"/>
                                    <div class="form-group col-md-6">
                                        <label>Title<span class="text-danger">*</span></label>
                                        <input type="text" value="{{ $view->title }}" class="form-control" id="title" name="title" placeholder="Title">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label>Slug<span class="text-danger">*</span></label>
                                        <input type="text" value="{{ substr($view->slug,1) }}" class="form-control" id="slug" name="slug" placeholder="Slug">
                                    </div>
                                    <div class="col-md-12 text-center">
                                        <button type="button" onclick="save()" class="btn btn-primary mr-2">Save</button>
                                        <a href="{{ route('view.index') }}" class="btn btn-light">Cancel</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @include('admin.partials.footer')            
        </div>
    </div>
    <script>
        $('#slug').on('keypress', function (event) {
            var regex = new RegExp("^[a-zA-Z0-9-]+$");
            var key = String.fromCharCode(!event.charCode ? event.which : event.charCode);
            if (!regex.test(key)) {
            event.preventDefault();
            return false;
            }
        });
        function save(){
            var formData  = new FormData(jQuery('#viewEdit')[0]);
            var id = document.getElementById("id").value;
            $.ajax({
                type:'POST',
                enctype: 'multipart/form-data',
                url:'<?php echo url('/');?>'+"/view/"+id,
                headers: {
                    'X-CSRF-Token': '{{ csrf_token() }}',
                },
                data: formData,
                contentType: false,
                processData: false,
                success:function(data){
                    console.log(data);
                    if(data == 'success'){
                        swal({
                            title: "Success",
                            text: "Data updated successfully.",
                            icon: "success",
                            buttons: "Ok",
                        })
                        .then((willDelete) => {
                            backUrl = (window.location+'').replace('/view/'+id+'/edit', '/view');
                            window.location.href = backUrl;
                        });
                    }else if(data == 'data found') {
                        swal({
                            title: "Error",
                            text: "Please enter different slug.",
                            icon: "error",
                            button: "Ok",
                        });
                    } else {
                        swal({
                            title: "Error",
                            text: "Please fill required fields.",
                            icon: "error",
                            button: "Ok",
                        });
                    }
                }
            });
        }
    </script>
@endsection

resources/views/admin/general/view/index.blade.php
@extends('admin.layouts.app')
@section('content')
    @include('admin.partials.navbar')
    <div class="container-fluid page-body-wrapper">
        @include('admin.partials.sidebar')
        <div class="main-panel">
        <div class="content-wrapper">
          <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-2 text-left">
                        <h4 class="card-title">View List</h4>
                    </div>
                    <div class="col-md-10 text-right mb-3">
                        <a href="{{ route('view.create') }}" class="btn btn-primary text-right">Create</a>
                    </div>
                </div>
              <div class="row">
                <div class="col-12">
                  <div class="table-responsive">
                    <table class="table table-bordered data-table">
                        <thead>
                            <tr>
                                <th width="100px">No</th>
                                <th>Title</th>
                                <th width="100px">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
        @include('admin.partials.footer')  
      </div>
    </div>
    <script type="text/javascript">
      setTimeout(() => {
        $(function () {
          var index = 0;
            var table = $('.data-table').DataTable({
                "order": [[ 0, "desc" ]],
                processing: true,
                serverSide: true,
                ajax: "{{ route('view.index') }}",
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'title', name: 'title'},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            });            
        });
      }, 500);
    </script>
    <script>
        function mdelete(id,mId){
          swal({
            title: "Are you sure?",
            text: "You want to delete this view?",
            icon: "warning",
            buttons: true,
            dangerMode: true,
          })
          .then((willDelete) => {
            if (willDelete) {
                $.ajax({
                  type:'DELETE',
                  enctype: 'multipart/form-data',
                  url:'<?php echo url('/');?>'+"/view/"+id,
                  headers: {
                      'X-CSRF-Token': '{{ csrf_token() }}',
                  },
                  data: {
                      id:id
                  },
                  contentType: false,
                  processData: false,
                  success:function(data){
                      if(data == 'success'){
                          swal({
                              title: "Success",
                              text: "View deleted successfully.",
                              icon: "success",
                              buttons: "Ok",
                          })
                          .then((willDelete) => {
                            var p=mId.parentNode.parentNode;
                            p.parentNode.removeChild(p);
                          });
                      } else {
                          swal({
                              title: "Error",
                              text: "Error occurred",
                              icon: "error",
                              button: "Ok",
                          });
                      }
                  }
              });
            } else {
              console.log("nothing delete");
            }
          });
        }
    </script>
@endsection